// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/ywardhana/chat/model"

// ChatUsecase is an autogenerated mock type for the ChatUsecase type
type ChatUsecase struct {
	mock.Mock
}

// CreateChat provides a mock function with given fields: message
func (_m *ChatUsecase) CreateChat(message string) *model.Chat {
	ret := _m.Called(message)

	var r0 *model.Chat
	if rf, ok := ret.Get(0).(func(string) *model.Chat); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Chat)
		}
	}

	return r0
}
