// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/ywardhana/chat/model"
import repository "github.com/ywardhana/chat/repository"

// ChatRepository is an autogenerated mock type for the ChatRepository type
type ChatRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: config
func (_m *ChatRepository) Get(config repository.ChatRepoConfig) ([]*model.Chat, error) {
	ret := _m.Called(config)

	var r0 []*model.Chat
	if rf, ok := ret.Get(0).(func(repository.ChatRepoConfig) []*model.Chat); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Chat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(repository.ChatRepoConfig) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewest provides a mock function with given fields:
func (_m *ChatRepository) GetNewest() *model.Chat {
	ret := _m.Called()

	var r0 *model.Chat
	if rf, ok := ret.Get(0).(func() *model.Chat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Chat)
		}
	}

	return r0
}

// Insert provides a mock function with given fields: _a0
func (_m *ChatRepository) Insert(_a0 *model.Chat) *repository.Chat {
	ret := _m.Called(_a0)

	var r0 *repository.Chat
	if rf, ok := ret.Get(0).(func(*model.Chat) *repository.Chat); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Chat)
		}
	}

	return r0
}
